import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {handleGitHub,safeReturnTo,allowedGitHubPath,unseal} from '../worker/github.mjs';
import {sqliteDB} from './sqlite-test-db.mjs';
const backend='https://auth.example',frontend='https://blaizzy.github.io/repometer/',page=frontend+'compare.html?left=Blaizzy%2Fmlx-vlm&right=Blaizzy%2Fmlx-audio',browserOrigin='https://blaizzy.github.io';
const random=()=>randomBytes(32).toString('base64url'),hash=value=>createHash('sha256').update(value).digest('base64url');
function fixture(){const env={DB:sqliteDB(),SITE_ORIGIN:backend,FRONTEND_URL:frontend,GITHUB_SESSION_KEY:random()};const calls=[];const fetchImpl=async(url,options)=>{calls.push({url,options});if(url.includes('/conversions'))return Response.json({client_id:'client-id',client_secret:'secret-test-only',name:'Repometer',id:12});if(url.endsWith('/access_token'))return Response.json({access_token:'github-token-test-only',expires_in:28800});if(url.endsWith('/user'))return Response.json({login:'Blaizzy',id:22});return Response.json({name:'mlx-audio',private:false},{headers:{'x-ratelimit-limit':'5000','x-ratelimit-remaining':'4998'}});};const request=(path,{cookie='',token='',method='GET',origin=browserOrigin,body,owner=false,email='owner@example.test'}={})=>handleGitHub(new Request(backend+path,{method,headers:{...(origin?{origin}:{}),cookie,...(token?{authorization:'Bearer '+token}:{}),...(owner?{'oai-authenticated-user-id':'owner-sub','oai-authenticated-user-email':email}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),env,{fetchImpl});return {env,calls,request};}
const cookie=r=>r.headers.getSetCookie().map(value=>value.split(';')[0]).filter(value=>!value.endsWith('=')).join('; ');
async function configure(f){f.env.GITHUB_CLIENT_ID='client-id';f.env.GITHUB_CLIENT_SECRET='secret-test-only';}
async function start(f){const verifier=random(),clientState=random();const response=await f.request('/auth/github/start?'+new URLSearchParams({returnTo:page,challenge:hash(verifier),client_state:clientState}));return {verifier,clientState,response,url:new URL(response.headers.get('location')),cookie:cookie(response)};}
async function callback(f,flow){const result=await f.request('/auth/github/callback?state='+flow.url.searchParams.get('state')+'&code=valid-github-code',{cookie:flow.cookie,origin:''});const destination=new URL(result.headers.get('location')),params=new URLSearchParams(destination.hash.slice(1));return {result,destination,code:params.get('oauth_code'),state:params.get('oauth_state')};}
async function login(f){await configure(f);const flow=await start(f),result=await callback(f,flow);const response=await f.request('/api/github/exchange',{method:'POST',body:{code:result.code,verifier:flow.verifier}});return {flow,result,response,...await response.json()};}

test('return URLs stay inside the Pages application and the GitHub proxy cannot target other APIs',()=>{const env={FRONTEND_URL:frontend};for(const value of ['https://evil.test/','https://blaizzy.github.io/other-project/','https://user@blaizzy.github.io/repometer/','//evil.test'])assert.equal(safeReturnTo(value,env),frontend);assert.equal(safeReturnTo(page+'&access_token=secret#token',env),page);for(const path of ['//evil.test/','/user','/repos/Blaizzy/mlx-vlm/issues','/repos/Blaizzy/mlx-vlm/../../user'])assert.equal(allowedGitHubPath(path),null);assert.equal(allowedGitHubPath('/repos/Blaizzy/mlx-vlm/commits/main'),'/repos/Blaizzy/mlx-vlm/commits/main');});
test('credentials come only from Worker secrets and forged platform headers cannot enable setup',async()=>{
  const f=fixture();
  for(const path of ['/auth/github/setup','/auth/github/setup/callback?state=fake&code=manifest-code']){
    assert.equal((await f.request(path)).status,404);
    assert.equal((await f.request(path,{owner:true})).status,404);
  }
  const initial=await (await f.request('/api/github/session',{owner:true})).json();
  assert.equal(initial.configured,false);assert.equal(initial.canSetup,false);
  await configure(f);
  const configured=await (await f.request('/api/github/session',{owner:true})).json();
  assert.equal(configured.configured,true);assert.equal(configured.canSetup,false);
  assert.ok(!JSON.stringify(configured).includes('secret-test-only'));
  assert.equal(f.calls.length,0);
});
test('OAuth state is bound to the browser and callbacks only issue one-time proof-key-bound tickets',async()=>{const f=fixture();await configure(f);const flow=await start(f),url='/auth/github/callback?state='+flow.url.searchParams.get('state')+'&code=valid-github-code';assert.equal((await f.request(url)).status,400);assert.equal(f.calls.length,0);const result=await callback(f,flow);assert.equal(result.destination.origin,browserOrigin);assert.equal(result.destination.pathname,'/repometer/compare.html');assert.equal(result.destination.search,new URL(page).search);assert.equal(result.state,flow.clientState);assert.ok(!result.destination.href.includes('github-token'));assert.match(result.code,/^[A-Za-z0-9_-]{43}$/);assert.equal(hash(JSON.parse(f.calls[0].options.body).code_verifier),flow.url.searchParams.get('code_challenge'));assert.equal((await f.request(url,{cookie:flow.cookie})).status,400);assert.equal((await f.request('/api/github/exchange',{method:'POST',body:{code:result.code,verifier:random()}})).status,401);const exchange=await f.request('/api/github/exchange',{method:'POST',body:{code:result.code,verifier:flow.verifier}});assert.equal(exchange.status,200);const data=await exchange.json();assert.match(data.sessionToken,/^[A-Za-z0-9_-]{43}$/);assert.equal(data.login,'Blaizzy');assert.ok(!JSON.stringify(data).includes('github-token'));assert.equal((await f.request('/api/github/exchange',{method:'POST',body:{code:result.code,verifier:flow.verifier}})).status,401);});
test('only the configured Pages origin can exchange tickets or use the authenticated proxy',async()=>{const f=fixture(),active=await login(f);const preflight=await f.request('/api/github',{method:'OPTIONS'});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),browserOrigin);assert.match(preflight.headers.get('access-control-allow-headers'),/Authorization/);assert.equal((await f.request('/api/github?path=%2Frepos%2FBlaizzy%2Fmlx-audio',{token:active.sessionToken,origin:'https://evil.test'})).status,403);const response=await f.request('/api/github?path=%2Frepos%2FBlaizzy%2Fmlx-audio',{token:active.sessionToken});assert.equal(response.status,200);assert.equal(f.calls.at(-1).options.headers.Authorization,'Bearer github-token-test-only');assert.equal(response.headers.get('x-ratelimit-limit'),'5000');assert.match(response.headers.get('access-control-expose-headers'),/x-ratelimit-limit/);assert.equal(response.headers.get('access-control-allow-origin'),browserOrigin);assert.equal(response.headers.get('set-cookie'),null);});
test('public status needs no workspace account; logout and expiry revoke opaque sessions',async()=>{const f=fixture();assert.equal((await (await f.request('/api/github/session')).json()).connected,false);const active=await login(f);assert.equal((await (await f.request('/api/github/session',{token:active.sessionToken})).json()).connected,true);assert.equal((await f.request('/api/github/logout',{method:'POST',token:active.sessionToken,origin:'https://evil.test'})).status,403);assert.equal((await f.request('/api/github/logout',{method:'POST',token:active.sessionToken})).status,200);assert.equal((await f.request('/api/github?path=%2Frepos%2FBlaizzy%2Fmlx-audio',{token:active.sessionToken})).status,401);const g=fixture(),expired=await login(g);g.env.DB.sqlite.exec('UPDATE github_sessions SET expires_at=0');assert.equal((await (await g.request('/api/github/session',{token:expired.sessionToken})).json()).connected,false);});
test('expired tickets and cancelled authorization cannot create usable sessions',async()=>{const f=fixture();await configure(f);const flow=await start(f),result=await callback(f,flow);f.env.DB.sqlite.exec('UPDATE oauth_transactions SET expires_at=0');assert.equal((await f.request('/api/github/exchange',{method:'POST',body:{code:result.code,verifier:flow.verifier}})).status,401);const next=await start(f);const cancelled=await f.request('/auth/github/callback?state='+next.url.searchParams.get('state')+'&error=access_denied',{cookie:next.cookie});assert.equal(cancelled.headers.get('location'),page+'&github_auth=cancelled');});

test('GitHub user tokens stay encrypted in D1 and outgoing requests do not follow redirects',async()=>{
  const f=fixture(),active=await login(f);
  const row=await f.env.DB.prepare('SELECT session_hash,user_id,token FROM github_sessions').first();
  assert.ok(!row.token.includes('github-token-test-only'));
  assert.equal(await unseal(row.token,f.env.GITHUB_SESSION_KEY,'session:'+row.user_id+':'+row.session_hash),'github-token-test-only');
  assert.ok(f.calls.every(call=>call.options.redirect==='manual'));
  assert.equal(active.response.status,200);
});
